### PR TITLE
typo

### PR DESCRIPTION
**Pull request by arghdos**

### CODE REVIEW

**Comment by arghdos** [comment]
Two minor bugs I encountered re-running performance data for the new paper.

- The first is just a silly mistake I made in fixing #26 (is_pdep -> pdep)
- The second has to do with an environment change on the testing machine, NVCC is now off the path such that I don't detect NVIDIA's OpenCL runtime (and this breaks the poorly formatted subprocess call, which should be fixed anyways)

**Comment by kyleniemeyer** [comment]
should bump the minor version number and issue a new release after merging this

**Comment by kyleniemeyer** [comment]
which reminds me, please update the CHANGELOG 😄

**Comment by arghdos** [comment]
@kyleniemeyer I think you need to issue the release IIRC, it's on your pypi account.
I updated the changelog and version

**Comment by kyleniemeyer** [comment]
I can do it, but the pip/conda release is done by Travis when it detects a new version tag, so it doesn't matter who does it.

**Comment by arghdos** [comment]
@kyleniemeyer not sure if that triggered it?

https://github.com/SLACKHA/pyJac/releases/tag/v1.0.6

**Pull request merged**
